base_url = "https://aidenfoxivey.com"
compile_sass = false
build_search_index = true
default_language = "en"

[markdown]
highlight_code = true

[extra]
# Put all your custom variables here
# generate_feed = true
